name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest  # Use windows-latest for a Windows environment
    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Adjust the Python version as needed

    - name: Install dependencies
      run: pip install pytest
  

    - name: List directory contents
      run: dir

    - name: Run tests
      run: pytest check/testd/test_calc.py  # Specify the test directory

    - name: Move test file if tests pass
      if: success()  # This step will only run if the previous step succeeds
      run: |
        if (!(Test-Path -Path "passed")) {
          New-Item -ItemType Directory -Path "passed"
        }
        Move-Item -Path "check\testd\test_calc.py" -Destination "passed\"
      shell: pwsh
      
    - name: Commit and push changes
      if: success()  # This step will only run if the tests succeed
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add passed/test_calc.py
        git commit -m "Move test_calc.py to passed folder after successful tests"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
