name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest  # Use windows-latest for a Windows environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Adjust the Python version as needed

    - name: Install dependencies
      run: pip install pytest
  

    - name: List directory contents
      run: dir

    - name: Run tests
      run: pytest testd  # Specify the test directory
